import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./components/mobile/Home/Header";
import { Footer } from "./components/mobile/Home/Footer";
import SeoWrapper from "./SeoWrapper";
import { Toaster } from "sonner";
import { NavigationBar } from "./components/mobile/Home/NavigationBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     <SeoWrapper/>
  
     
        
        {children}
                <Toaster richColors position="top-center" />
             
     
      </body>
    </html>
  );
}
